### PR TITLE
Test with GHC 8.6.1

### PR DESCRIPTION
**Pull request by vaibhavsagar**

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
Thanks!

**Comment by sjakobi** [comment]
Now that ghc-8.6-beta1 is out, can we get a release including this change?

**Comment by svenpanne** [comment]
Done: http://hackage.haskell.org/package/StateVar

Now somebody really needs to nudge the `stm` people to make a release which is compatible with GHC 8.6, their package is currently blocking hundreds of other packages... :cry:

**Comment by sjakobi** [comment]
As a builtin package `stm` will be released in sync with GHC-8.6, I believe.

**Comment by svenpanne** [comment]
> As a builtin package stm will be released in sync with GHC-8.6, I believe.

OK, it seems that things work now with 8.6, previously they didn't: https://travis-ci.org/haskell-opengl/OpenGL/jobs/408950735

The `stm` owners are just lazy again, the version shipped with 8.6 has not yet been release to Hackage, which is a bit confusing... :confused:

**Pull request merged**
